# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:               Rahul Mehta
tagline:             'Notes from and after a Bioengineering PhD'
description:         'A blog that keeps notes and ideas during and after my PhD.'
url:                 'http://rmehta1987.github.io'
baseurl:            'http://rmehta1987.github.io'
paginate:            5

# About/contact
author:
  name:              Rahul Mehta
  email:             mehta5[at]uic[dot]edu

collections:
  tips:
    output: true
    layout: page
    show_sidebar: true
  publications:
    output: true
    layout: page
    show_sidebar: true

# Social
social-network-links:
  github: http://github.com/rmehta1987
  linkedin: https://www.linkedin.com/in/rmehta1987/
share-links-active:
  linkedin: true
  github: true
